FROM node:20-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY www/package.json www/package-lock.json* ./

RUN npm ci

COPY www .

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "run", "dev"]
